# Generated by Django 4.0.6 on 2022-08-16 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='creat_time',
            new_name='create_time',
        ),
    ]
